"""actualizacion de relacion entre producto y categoria



Revision ID: 1dc555bdf70e
Revises: a4b926f46c23
Create Date: 2026-05-31 15:54:02.187130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc555bdf70e'
down_revision: Union[str, Sequence[str], None] = 'a4b926f46c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categorias_id_producto_fkey'), 'categorias', type_='foreignkey')
    op.drop_column('categorias', 'id_producto')
    op.add_column('productos', sa.Column('id_categoria', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'productos', 'categorias', ['id_categoria'], ['id_categoria'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'id_categoria')
    op.add_column('categorias', sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('categorias_id_producto_fkey'), 'categorias', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')
    # ### end Alembic commands ###
