"""add titulo index

Revision ID: 3a9d89b0c5d5
Revises: dfb88bc81ef3
Create Date: 2026-06-21 18:35:58.182256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9d89b0c5d5'
down_revision: Union[str, Sequence[str], None] = 'dfb88bc81ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_productos_titulo_lower', 'productos', [sa.literal_column('lower(titulo)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_titulo_lower', table_name='productos')
    # ### end Alembic commands ###
