"""actualizar modelos producto ranking

Revision ID: 5e4b6a839023
Revises: d0e84face121
Create Date: 2026-06-14 19:36:36.450856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4b6a839023'
down_revision: Union[str, Sequence[str], None] = 'd0e84face121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_id_categoria'), 'productos', ['id_categoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_id_categoria'), table_name='productos')
    # ### end Alembic commands ###
