"""create imagenes table

Revision ID: 5fd9d85abdc5
Revises: eba397c6d1d4
Create Date: 2026-06-22 02:08:56.527131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd9d85abdc5'
down_revision: Union[str, Sequence[str], None] = 'eba397c6d1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagenes', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagenes', sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
