"""actualizacion de relacion ranking y categoria

Revision ID: 658c4b856051
Revises: c54f483c75f2
Create Date: 2026-06-15 17:36:45.652700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658c4b856051'
down_revision: Union[str, Sequence[str], None] = 'c54f483c75f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranking', sa.Column('id_categoria', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_ranking_categoria_posicion'), table_name='ranking')
    op.create_index('idx_ranking_categoria_posicion', 'ranking', ['id_categoria', 'posicion'], unique=False)
    op.create_foreign_key(None, 'ranking', 'categorias', ['id_categoria'], ['id_categoria'], ondelete='CASCADE')
    op.drop_column('ranking', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranking', sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ranking', type_='foreignkey')
    op.drop_index('idx_ranking_categoria_posicion', table_name='ranking')
    op.create_index(op.f('idx_ranking_categoria_posicion'), 'ranking', ['categoria', 'posicion'], unique=False)
    op.drop_column('ranking', 'id_categoria')
    # ### end Alembic commands ###
