"""agregar_search_vector_a_productos

Revision ID: 8a5854a8cd30
Revises: 5e4b6a839023
Create Date: 2026-06-15 17:20:32.879851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a5854a8cd30'
down_revision: Union[str, Sequence[str], None] = '5e4b6a839023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'search_vector')
    # ### end Alembic commands ###
