"""add_index_to_id_categoria_in_productos

Revision ID: 9c5df7de4aa3
Revises: 
Create Date: 2026-06-10 18:22:09.990325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5df7de4aa3'
down_revision: Union[str, Sequence[str], None] = '1f8d522c4873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_id_categoria'), 'productos', ['id_categoria'], unique=False)
    op.create_index('idx_ranking_categoria_posicion', 'ranking', ['categoria', 'posicion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ranking_categoria_posicion', table_name='ranking')
    op.drop_index(op.f('ix_productos_id_categoria'), table_name='productos')
    # ### end Alembic commands ###
