"""First migration

Revision ID: a4b926f46c23
Revises: 
Create Date: 2026-05-27 19:27:08.862168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b926f46c23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('categoria_principal', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_productos_asin'), 'productos', ['asin'], unique=True)
    op.create_table('atributos',
    sa.Column('id_atributo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_atributo')
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('ranking',
    sa.Column('id_ranking', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ranking')
    )
    op.create_table('relaciones',
    sa.Column('id_relacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('asin_relacionado', sa.String(length=20), nullable=False),
    sa.Column('tipo_relacion', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_relacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relaciones')
    op.drop_table('ranking')
    op.drop_table('categorias')
    op.drop_table('atributos')
    op.drop_index(op.f('ix_productos_asin'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
