"""ranking one to one

Revision ID: d0e84face121
Revises: 9c5df7de4aa3
Create Date: 2026-06-10 19:54:40.704101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e84face121'
down_revision: Union[str, Sequence[str], None] = '9c5df7de4aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_id_categoria'), table_name='productos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_id_categoria'), 'productos', ['id_categoria'], unique=False)
    # ### end Alembic commands ###
