"""add gin and trigram indexes

Revision ID: dfb88bc81ef3
Revises: ab1fdd72105a
Create Date: 2026-06-20 23:50:31.948696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb88bc81ef3'
down_revision: Union[str, Sequence[str], None] = 'ab1fdd72105a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_productos_search_vector'), table_name='productos', postgresql_using='gin')
    op.create_index('ix_productos_search_vector', 'productos', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_productos_titulo_trgm', 'productos', ['titulo'], unique=False, postgresql_using='gin', postgresql_ops={'titulo': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_titulo_trgm', table_name='productos', postgresql_using='gin', postgresql_ops={'titulo': 'gin_trgm_ops'})
    op.drop_index('ix_productos_search_vector', table_name='productos', postgresql_using='gin')
    op.create_index(op.f('idx_productos_search_vector'), 'productos', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
