"""add imagen table

Revision ID: eba397c6d1d4
Revises: 0ebacfcb635a
Create Date: 2026-06-22 01:57:57.435536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba397c6d1d4'
down_revision: Union[str, Sequence[str], None] = '0ebacfcb635a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    # ### end Alembic commands ###
