"""actualizacion de tabla categoria

Revision ID: ec746454cf50
Revises: a86221abf790
Create Date: 2026-06-13 17:01:37.244326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec746454cf50'
down_revision: Union[str, Sequence[str], None] = 'a86221abf790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productos_id_categoria'), 'productos', ['id_categoria'], unique=False)
    op.drop_column('productos', 'categoria_principal')
    op.create_index('idx_ranking_categoria_posicion', 'ranking', ['categoria', 'posicion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ranking_categoria_posicion', table_name='ranking')
    op.add_column('productos', sa.Column('categoria_principal', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productos_id_categoria'), table_name='productos')
    # ### end Alembic commands ###
