version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    image: grupo8-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mired

  frontend:
    build:
      context: ../frontend # 👈 Sale de 'docker/' y entra directo a 'frontend/'
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Tu web se abrirá en http://localhost:8080
    depends_on:
      - backend
    networks:
      - mired

  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: redis-server --requirepass sebicho123  # Le seteamos la clave oficial
    ports:
      - "6379:6379"
    networks:
      - mired
      
networks:
  mired:
    external: true
