version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    image: grupo8-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - mired

  frontend:
    build:
      context: ../frontend # 👈 Sale de 'docker/' y entra directo a 'frontend/'
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Tu web se abrirá en http://localhost:8080
    depends_on:
      - backend
    networks:
      - mired

networks:
  mired:
    external: true
