from app.repositories.categoria_repository import categoria_repo
from app.repositories.atributos_repository import atributo_repo
from app.repositories.producto_repository import producto_repo
from app.repositories.ranking_repository import ranking_repo